ci: checking variable definitions

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -6,11 +6,15 @@ pipelines:
             - step:
                   name: 'Checking for release commit'
                   script:
+                      - echo $BITBUCKET_COMMIT
                       - |
                           if [[ $(git log $BITBUCKET_COMMIT -1 --oneline) =~ ^.*chore\\(release\\).*$ ]]; then
                             echo $(git log $BITBUCKET_COMMIT -1 --oneline);
                             echo true > condition.txt;
                           fi
+                      - ls -alF
+                      - echo "Failing early to check only this step";
+                      - exit 1;
                   artifacts:
                       - condition.txt
             - step:
